#site basic info setting:
baseurl: '/nl' # for http://your-github-name.github.io/project-name
site_name: Site Name
description: ''
author:
  name: Author Name
  email: email@email.com
  github: github
  twitter: twitter
  bio: bio description
##site basic info setting

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
categories_path: categories.html
tags_path: tags.html
rss_path: feed.xml

markdown: redcarpet
pygments: true
